### ISSUE TITLE
about bottom Indicator Height

### ISSUE THREAD

**Issue by lizheftd** [squarezw/ZWSlideViewController#2]
How to modify the bottom Indicator Height  :)

**Comment by squarezw** [comment]
i exposed height property of the indicator from this [commit](https://github.com/squarezw/ZWSlideViewController/commit/cc30eb1e13392c4bed2a81f980f740d89c6f8b8c)

you could check out latest codes on master branch.

**Comment by lizheftd** [comment]
thanks
