### ISSUE TITLE
当我的标题太少时，处理得不好

### ISSUE THREAD

**Issue by q351941406** [squarezw/ZWSlideViewController#3]
当我的标题只有3个时，标题并不能在屏幕的宽度下平铺，而是集中在中间去了，这非常不好，希望改进，或提供个方法可以设置的

**Comment by q351941406** [comment]
itemLabel.textAlignment = NSTextAlignmentCenter;     建议加上这句

**Comment by squarezw** [comment]
如果你是想平均分配每个 item label 时，你可以用 item size, 每个item 的width 由你自己估算而来 。如：
`self.sectionBar.itemSize` = CGSizeMake(屏幕宽/你的元素个数, 64);` 

因为使用的场景各不相同，所以这里暂时没有提供统一的处理方式。

`itemLabel.textAlignment = NSTextAlignmentCenter` 已经在最新的 master 分支上了。

**Comment by q351941406** [comment]
是的，我是设置了itemSize，但还要文字居中才行，你已经加了的话，就请麻烦更新下pod吧，谢谢

**Comment by squarezw** [comment]
Pod 已更析到了 0.1.3

**Comment by q351941406** [comment]
谢谢。辛苦了

**Comment by squarezw** [comment]
谢谢你的建议！
