### ISSUE TITLE
'ZWSlideViewController.h' file not found

### ISSUE THREAD

**Issue by EggmanQi** [squarezw/ZWSlideViewController#6]
'ZWSlideViewController.h' file not found

Using ZWSlideViewController (0.1.3)，xcode 7.3.1。
使用是出现上面的错误， `#import <ZWSlideViewController/ZWSlideViewController.h>`，这样也不行。

**Comment by squarezw** [comment]
你是用什么方式引入的？

**Comment by EggmanQi** [comment]
cocoapod

**Comment by squarezw** [comment]
你好，引入的头文件是 ZWSViewController.h ，不好意思，没有以 lib 库文件命名。
