### ISSUE TITLE
希望改进

### ISSUE THREAD

**Issue by q351941406** [squarezw/ZWSlideViewController#7]
如果我是异步掉refreshViews方法刷新，刷新后的试图会覆盖我刷新前添加的控件，我屏幕上有一个按钮，刷新后4个tableView把我按钮都挡住了，你应该把tableView放到最下面。

**Comment by squarezw** [comment]
谢谢你的建议，就目前来说，确实是这样的，不过你可以拿到 sectionBar 和 pagingView。将它置于你想要的视图层级中。

**Comment by q351941406** [comment]
我只有把按钮的添加延迟到了网络请求后。暂时解决了问题，辛苦了，谢谢你的框架
