### ISSUE TITLE
IOS 10适配问题

### ISSUE THREAD

**Issue by q351941406** [squarezw/ZWSlideViewController#8]
if ([[[UIDevice currentDevice] systemVersion] compare:@"7.0"] != NSOrderedAscending) {
        self.edgesForExtendedLayout = UIRectEdgeNone;
    }
这个代码要打开，不然在IOS 10中会往上跑，必须self.edgesForExtendedLayout = UIRectEdgeNone;，

**Comment by squarezw** [comment]
感谢你的反馈。这个问题已在 0.1.4 版本中修复。

**Comment by q351941406** [comment]
辛苦了
