### ISSUE TITLE
Select multiple indexes if i will select from menu bar.

### ISSUE THREAD

**Issue by mehmoodbahria** [squarezw/ZWSlideViewController#9]
For example i am at index 1 and i select index 10 from menu bar what it will do is first select next to 1 which is 2 and then select previous to 10 which is 9 and at the last it will select the desire index which is 10.I want if i select 10th index from menu it must land on 10th index not select any other index.

**Comment by squarezw** [comment]
thanks for your feedback.  before i used a strategy which could load previous and next page as a cache page .   generally we will scroll it from left to right step by step with gesture  .  

however you mentioned me there are probably the potential issues .  i will have a look later.   maybe i will add some switcher to console it.

**Comment by mehmoodbahria** [comment]
Thanks and Thanks for your quick response very much appreciated.

**Comment by squarezw** [comment]
Hi. mehmoodbahria. 

i just added a property of "`preload`" to control whether the cached strategy is enabled for next page.

and the default value is `NO`. which means **you do not need add any codes to solve your problem. just pull the latest codes on the master branch to test it .** 2f0bc31aef38dcd2fd5a9c19fdfdc49efb6937c1

BTW.  what if you want to open it , you could add the following codes in you `viewDidLoad` method. 

i.e: `self.pagingView.preload = NO`
